### PR TITLE
Multi schedulers

### PR DESCRIPTION
**Pull request by marcinn**
Here is an updated PR for multiple schedulers support (GH-104).

refs #70

### CODE REVIEW

**Comment by selwin** [comment]
@marcinn could you please restore `register_birth()` and `register_death()`? `register_birth()` should still be called after lock is acquired and `register_death()` called when scheduler stops.

**Comment by marcinn** [comment]
OK, I'll look at this. I've just resolved the conflict without looking at birth/death.

**Comment by marcinn** [comment]
@selwin  I'm thinking over and over again about scheduler locking and I'm not sure about current implementation. The lock is acquired in the loop and stays acquired until end of the work. So in non-burst mode it will be locked constantly, even during sleeping. 

Maybe the lock should be released before scheduler is going to sleep? It would allow other long-running schedulers to run. The one risk I see relies in not synced clocks between hosts running the scheduler, where each instance may enqueue too many jobs.

What do you think?

**Comment by selwin** [comment]
@marcinn I see your point. However, I'm more inclined to leave it as it now.

People mostly request this feature for redundancy reasons. If a scheduler releases its lock everytime it goes to sleep, people with multiple schedulers will have many schedulers firing off at random times, which is not what we want.

**Comment by marcinn** [comment]
Thank you, @selwin

**Pull request merged**
