### PR TITLE
Fixes in Scheduler.cron()

### PR DESCRIPTION
**Pull request by lechup**
This PR includes fixes in Scheduler.cron():
* added description argument
* added some tests
* added timeout argument - it includes #114 prepared by @csaba-stylight 
* result_ttl default to -1 - it includes #115 prepared by @csaba-stylight

Those are not included as it turned out it doesn't make sense (as discussed below):
* ~~added result_ttl argument~~
* ~~added ttl argument~~

### CODE REVIEW

**Comment by csaba-stylight** [comment]
Allowing the `result_ttl` to be set by the caller provides the maximum flexibility, but what is the use case behind it?

`Scheduler.cron` is meant to be used for periodic tasks. If `result_ttl >= 0`, the caller *must* make sure that the job period is small than `result_ttl`, otherwise the job gets executed only once. At the very least this should be noted in the docstring.

I recommend having `-1` as the default value for `result_ttl`, so that calls like

`cron('*/15 * * * *', job_func)`

work as expected. With `result_ttl=None` the job above would get executed only once (because `result_ttl=None` actually means "use the default result TTL", which is 500 sec).

**Comment by lechup** [comment]
Won't setting `result_ttl=-1` result in keeping all cron results infinitely?

**Comment by lechup** [comment]
Hm... ok, I think now I get it. We can default to `-1` because we always use same job id so it will be just one result kept in redis.

**Comment by csaba-stylight** [comment]
Yes, but for periodic jobs we need that. The `Scheduler.schedule` does the same thing if `interval` is set, see https://github.com/ui/rq-scheduler/blob/master/rq_scheduler/scheduler.py#L137.

This all boils down to this: https://github.com/nvie/rq/blob/master/rq/worker.py#L608

The main problem here is, that the job and the job result is the same thing. You want to cancel the job result, you need to cancel the job. `rq` will problably change this in the future.

**Comment by lechup** [comment]
Ok, so it does not make any sense to set `result_ttl` to something different from `-1`.

Hm... just wondering why we have `result_ttl` in `Scheduler.schedule`? Just for the case we do not provide inverval?

What do You think about others `ttl` and `description` in case of `Scheduler.cron()`?

**Comment by csaba-stylight** [comment]
The TTL stuff makes sense when `Scheduler.schedule` is used to schedule non-periodic jobs. With periodic jobs is like trying to shoot yourself in the foot ;).

Setting TTL values via `Scheduler.cron` currently doesn't make sense because the bad support for periodic jobs from `rq`.

As for `description`: looks fine.

**Comment by lechup** [comment]
@csaba-stylight: Ok that make sense.

Hm... If You want I can base on Your PR so we could close Yours?

**Comment by csaba-stylight** [comment]
Sure, go ahead.

**Comment by lechup** [comment]
@csaba-stylight what do You think now? I've included #114 and #115 + added description arguments and some tests...

Do You think we can close #114 and #115 and leave this one open?

**Comment by selwin** [comment]
Thanks for the PR!

**Comment by lockie** [comment]
Hello!
> added timeout argument

Perhaps worth documenting in readme? Took me a while to find out that this possibility exists.

**Pull request merged**
