### PR TITLE
Added support for setting the job timeout when scheduling jobs via cron.

### PR DESCRIPTION
**Pull request by csaba-stylight**
While this adds support for `timeout` only, why is `cron` missing the other relevant parameters (`ttl`, `id` and `description`)?

### CODE REVIEW

**Comment by selwin** [comment]
Thanks for the PR! Can you please resolve the merge conflict so I can pull this in?

**Comment by lechup** [comment]
@csaba-stylight ping :+1:

**Comment by csaba-stylight** [comment]
Resolved merge conflicts.

**Comment by lechup** [comment]
Thanks!

**Comment by lechup** [comment]
@selwin @csaba-stylight I've prepared #120 which includes also this one...

**Pull request merged**
